# Product Endpoints

/products:
  get:
    tags:
      - Products
    summary: Get all products with search and filtering
    description: Retrieves a list of products with optional search, filtering, and pagination
    parameters:
      - in: query
        name: search
        schema:
          type: string
        description: Search term for product name or description
        example: "Nike Air"
      - in: query
        name: category
        schema:
          type: string
        description: Filter by category ID
      - in: query
        name: minPrice
        schema:
          type: number
        description: Minimum price filter
      - in: query
        name: maxPrice
        schema:
          type: number
        description: Maximum price filter
      - in: query
        name: size
        schema:
          type: string
          enum: [UK6, UK7, UK8, UK9, UK10, UK11]
        description: Filter by shoe size
      - in: query
        name: color
        schema:
          type: string
          enum: [RED, BLACK, WHITE, BLUE, GREEN, YELLOW, GREY]
        description: Filter by shoe color
      - in: query
        name: page
        schema:
          type: integer
          minimum: 1
          default: 1
        description: Page number for pagination
      - in: query
        name: limit
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        description: Number of products per page
    responses:
      '200':
        description: Products retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsListResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                products:
                  - id: "cm1234567890"
                    name: "Nike Air Force 1"
                    description: "Classic white sneakers"
                    brand: "Nike"
                    price: 89.99
                    stock: 50
                    images: ["https://example.com/image1.jpg"]
                    categories: []
                    variants:
                      - size: "UK9"
                        color: "WHITE"
                        stock: 25
                      - size: "UK10"
                        color: "WHITE"
                        stock: 25
                    vendor:
                      id: "vendor123"
                      name: "Nike Store"
                      email: "vendor@nike.com"
                    created_at: "2023-10-01T10:00:00.000Z"
                    updated_at: "2023-10-01T10:00:00.000Z"
                pagination:
                  page: 1
                  limit: 10
                  total: 100
                  totalPages: 10
                message: "Products retrieved successfully"
              api_error: null
      '500':
        description: Internal server error
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  post:
    tags:
      - Products
    summary: Create a new product (Vendor only)
    description: Creates a new product. Only vendors can create products.
    security:
      - bearerAuth: []
      - cookieAuth: []
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/CreateProductRequest'
              - type: object
                properties:
                  image:
                    type: string
                    format: binary
                    description: Product image file
    responses:
      '201':
        description: Product created successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductCreateResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                product:
                  id: "cm1234567890"
                  name: "Nike Air Force 1"
                  description: "Classic white sneakers"
                  brand: "Nike"
                  price: 89.99
                  stock: 50
                  images: ["https://example.com/image1.jpg"]
                  categories: []
                  variants:
                    - size: "UK9"
                      color: "WHITE"
                      stock: 25
                    - size: "UK10"
                      color: "WHITE"
                      stock: 25
                  vendor:
                    id: "vendor123"
                    name: "Nike Store"
                    email: "vendor@nike.com"
                  created_at: "2023-10-01T10:00:00.000Z"
                  updated_at: "2023-10-01T10:00:00.000Z"
                message: "Product created successfully"
              api_error: null
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '403':
        description: Forbidden - Not a vendor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '400':
        description: Bad request - Invalid input
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/products/{id}:
  get:
    tags:
      - Products
    summary: Get product by ID
    description: Retrieves a specific product by its ID
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Product ID
        example: "cm1234567890"
    responses:
      '200':
        description: Product retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                product:
                  id: "cm1234567890"
                  name: "Nike Air Force 1"
                  description: "Classic white sneakers"
                  brand: "Nike"
                  price: 89.99
                  stock: 50
                  images: ["https://example.com/image1.jpg"]
                  categories: []
                  variants:
                    - size: "UK9"
                      color: "WHITE"
                      stock: 25
                    - size: "UK10"
                      color: "WHITE"
                      stock: 25
                  vendor:
                    id: "vendor123"
                    name: "Nike Store"
                    email: "vendor@nike.com"
                  created_at: "2023-10-01T10:00:00.000Z"
                  updated_at: "2023-10-01T10:00:00.000Z"
              api_error: null
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  put:
    tags:
      - Products
    summary: Update product (Vendor only)
    description: Updates a product. Only the vendor who created the product can update it.
    security:
      - bearerAuth: []
      - cookieAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Product ID
        example: "cm1234567890"
    requestBody:
      required: true
      content:
        multipart/form-data:
          schema:
            allOf:
              - $ref: '#/components/schemas/CreateProductRequest'
              - type: object
                properties:
                  image:
                    type: string
                    format: binary
                    description: Product image file
    responses:
      '200':
        description: Product updated successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                product:
                  id: "cm1234567890"
                  name: "Nike Air Force 1"
                  description: "Classic white sneakers"
                  brand: "Nike"
                  price: 89.99
                  stock: 50
                  images: ["https://example.com/image1.jpg"]
                  categories: []
                  variants:
                    - size: "UK9"
                      color: "WHITE"
                      stock: 25
                    - size: "UK10"
                      color: "WHITE"
                      stock: 25
                  vendor:
                    id: "vendor123"
                    name: "Nike Store"
                    email: "vendor@nike.com"
                  created_at: "2023-10-01T10:00:00.000Z"
                  updated_at: "2023-10-01T10:00:00.000Z"
                message: "Product updated successfully"
              api_error: null
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '403':
        description: Forbidden - Not the product owner
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

  delete:
    tags:
      - Products
    summary: Delete product (Vendor only)
    description: Deletes a product. Only the vendor who created the product can delete it.
    security:
      - bearerAuth: []
      - cookieAuth: []
    parameters:
      - in: path
        name: id
        required: true
        schema:
          type: string
        description: Product ID
        example: "cm1234567890"
    responses:
      '200':
        description: Product deleted successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BasicSuccessResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                message: "Product deleted successfully"
              api_error: null
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '403':
        description: Forbidden - Not the product owner
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '404':
        description: Product not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/products/categories/{categoryId}:
  get:
    tags:
      - Products
    summary: Get products by category
    description: Retrieves all products in a specific category
    parameters:
      - in: path
        name: categoryId
        required: true
        schema:
          type: string
        description: Category ID
        example: "cat123"
      - in: query
        name: page
        schema:
          type: integer
          minimum: 1
          default: 1
        description: Page number for pagination
      - in: query
        name: limit
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        description: Number of products per page
    responses:
      '200':
        description: Products retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsListResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                products:
                  - id: "cm1234567890"
                    name: "Nike Air Force 1"
                    description: "Classic white sneakers"
                    brand: "Nike"
                    price: 89.99
                    stock: 50
                    images: ["https://example.com/image1.jpg"]
                    categories: []
                    variants:
                      - size: "UK9"
                        color: "WHITE"
                        stock: 25
                      - size: "UK10"
                        color: "WHITE"
                        stock: 25
                    vendor:
                      id: "vendor123"
                      name: "Nike Store"
                      email: "vendor@nike.com"
                    created_at: "2023-10-01T10:00:00.000Z"
                    updated_at: "2023-10-01T10:00:00.000Z"
                pagination:
                  page: 1
                  limit: 10
                  total: 25
                  totalPages: 3
                message: "Products retrieved successfully"
              api_error: null
      '404':
        description: Category not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/products/vendor/my-products:
  get:
    tags:
      - Products
    summary: Get vendor's products
    description: Retrieves all products created by the authenticated vendor
    security:
      - bearerAuth: []
      - cookieAuth: []
    parameters:
      - in: query
        name: page
        schema:
          type: integer
          minimum: 1
          default: 1
        description: Page number for pagination
      - in: query
        name: limit
        schema:
          type: integer
          minimum: 1
          maximum: 100
          default: 10
        description: Number of products per page
    responses:
      '200':
        description: Vendor products retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsListResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                products:
                  - id: "cm1234567890"
                    name: "Nike Air Force 1"
                    description: "Classic white sneakers"
                    brand: "Nike"
                    price: 89.99
                    stock: 50
                    images: ["https://example.com/image1.jpg"]
                    categories: []
                    variants:
                      - size: "UK9"
                        color: "WHITE"
                        stock: 25
                      - size: "UK10"
                        color: "WHITE"
                        stock: 25
                    vendor:
                      id: "vendor123"
                      name: "Nike Store"
                      email: "vendor@nike.com"
                    created_at: "2023-10-01T10:00:00.000Z"
                    updated_at: "2023-10-01T10:00:00.000Z"
                pagination:
                  page: 1
                  limit: 10
                  total: 15
                  totalPages: 2
                message: "Products retrieved successfully"
              api_error: null
      '401':
        description: Unauthorized
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'
      '403':
        description: Forbidden - Not a vendor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'

/products/vendor/{vendorId}:
  get:
    tags:
      - Products
    summary: Get products by vendor (public)
    description: Retrieves all products from a specific vendor (public access)
    parameters:
      - in: path
        name: vendorId
        required: true
        schema:
          type: string
        description: Vendor ID to get products for
        example: "vendor123"
    responses:
      '200':
        description: Vendor products retrieved successfully
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductsListResponse'
            example:
              local_date_time: "2025-10-04T10:00:00.000Z"
              data:
                products:
                  - id: "cm1234567890"
                    name: "Nike Air Force 1"
                    description: "Classic white sneakers"
                    brand: "Nike"
                    price: 89.99
                    stock: 50
                    images: ["https://example.com/image1.jpg"]
                    categories: []
                    variants:
                      - size: "UK9"
                        color: "WHITE"
                        stock: 25
                      - size: "UK10"
                        color: "WHITE"
                        stock: 25
                    vendor:
                      id: "vendor123"
                      name: "Nike Store"
                      email: "vendor@nike.com"
                    created_at: "2023-10-01T10:00:00.000Z"
                    updated_at: "2023-10-01T10:00:00.000Z"
                pagination:
                  page: 1
                  limit: 10
                  total: 50
                  totalPages: 5
                message: "Vendor products retrieved successfully"
              api_error: null
      '404':
        description: Vendor not found
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ErrorResponse'